/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.bits.bee.plugintraining.ui;

import com.bits.bee.plugintraining.bl.Pegawai;
import com.bits.bee.plugintraining.ui.dlg.DlgPegawai;
import com.bits.bee.ui.UIMgr;
import com.bits.bee.ui.myswing.InternalFrameTrans;
import com.bits.lib.BUtil;
import com.bits.lib.dbswing.BdbState;
import com.bits.lib.security.BAuthMgr;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import org.openide.util.Exceptions;

/**
 *
 * @author Sigit Sukarman
 */
public class FrmPegawai extends InternalFrameTrans implements PropertyChangeListener {

    String OBJID = "PG-TR-02";
    Pegawai emp = new Pegawai();
    BdbState state = new BdbState();

    /**
     * Creates new form FrmPegawai
     */
    public FrmPegawai() {
        initComponents();
        initMaster();
    }

    private void initMaster() {
        jBToolbar3.setState(state);
        jBToolbar3.setObjid(OBJID);
        jBToolbar3.setAuthMgr(BAuthMgr.getDefault());

        state.addPropertyChangeListener("state", this);
        state.setState(BdbState.stNONE);
    }

    private void initPanel(boolean enable) {
        BUtil.setEnabledPanel(jPanel2, enable);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBToolbar3 = new com.bits.lib.dbswing.JBToolbar();
        jFormLabel1 = new com.bits.bee.ui.myswing.JFormLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        bTextIDField3 = new com.bits.bee.ui.myswing.BTextIDField();
        jLabel2 = new javax.swing.JLabel();
        txtEmpName = new com.bits.lib.dbswing.JBdbTextField();
        jLabel3 = new javax.swing.JLabel();
        TxtPhone = new com.bits.lib.dbswing.JBdbTextField();
        jLabel4 = new javax.swing.JLabel();
        txtMobile = new com.bits.lib.dbswing.JBdbTextField();
        jLabel5 = new javax.swing.JLabel();
        txtEmail = new com.bits.lib.dbswing.JBdbTextField();
        txtAlamat = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jdbTextArea1 = new com.borland.dbswing.JdbTextArea();
        txtCity = new javax.swing.JLabel();
        jCboCity1 = new com.bits.bee.ui.myswing.JCboCity();

        setTitle(org.openide.util.NbBundle.getMessage(FrmPegawai.class, "FrmPegawai.title")); // NOI18N

        jBToolbar3.setEnablePrint(false);
        jBToolbar3.setEnableRefresh(false);
        jBToolbar3.setEnableVoid(false);
        jBToolbar3.addJBToolbarListener(new com.bits.lib.dbswing.JBToolbarListener() {
            public void toolbarNewPerformed(com.bits.lib.dbswing.JBToolbarEvent evt) {
                jBToolbar3ToolbarNewPerformed(evt);
            }
            public void toolbarOpenPerformed(com.bits.lib.dbswing.JBToolbarEvent evt) {
                jBToolbar3ToolbarOpenPerformed(evt);
            }
            public void toolbarEditPerformed(com.bits.lib.dbswing.JBToolbarEvent evt) {
                jBToolbar3ToolbarEditPerformed(evt);
            }
            public void toolbarSavePerformed(com.bits.lib.dbswing.JBToolbarEvent evt) {
                jBToolbar3ToolbarSavePerformed(evt);
            }
            public void toolbarCancelPerformed(com.bits.lib.dbswing.JBToolbarEvent evt) {
                jBToolbar3ToolbarCancelPerformed(evt);
            }
            public void toolbarDeletePerformed(com.bits.lib.dbswing.JBToolbarEvent evt) {
                jBToolbar3ToolbarDeletePerformed(evt);
            }
            public void toolbarVoidPerformed(com.bits.lib.dbswing.JBToolbarEvent evt) {
            }
            public void toolbarPrintPerformed(com.bits.lib.dbswing.JBToolbarEvent evt) {
            }
            public void toolbarRefreshPerformed(com.bits.lib.dbswing.JBToolbarEvent evt) {
            }
        });

        jFormLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        jFormLabel1.setText(org.openide.util.NbBundle.getMessage(FrmPegawai.class, "FrmPegawai.jFormLabel1.text")); // NOI18N

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setForeground(new java.awt.Color(153, 153, 153));

        jLabel1.setFont(new java.awt.Font("Bitstream Vera Sans", 0, 11)); // NOI18N
        jLabel1.setText(org.openide.util.NbBundle.getMessage(FrmPegawai.class, "FrmPegawai.jLabel1.text")); // NOI18N

        bTextIDField3.setText(org.openide.util.NbBundle.getMessage(FrmPegawai.class, "FrmPegawai.bTextIDField3.text")); // NOI18N
        bTextIDField3.setColumnName(org.openide.util.NbBundle.getMessage(FrmPegawai.class, "FrmPegawai.bTextIDField3.columnName")); // NOI18N
        bTextIDField3.setDataSet(emp.getDataSet());
        bTextIDField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTextIDField3ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Bitstream Vera Sans", 0, 11)); // NOI18N
        jLabel2.setText(org.openide.util.NbBundle.getMessage(FrmPegawai.class, "FrmPegawai.jLabel2.text")); // NOI18N

        txtEmpName.setText(org.openide.util.NbBundle.getMessage(FrmPegawai.class, "FrmPegawai.txtEmpName.text")); // NOI18N
        txtEmpName.setColumnName(org.openide.util.NbBundle.getMessage(FrmPegawai.class, "FrmPegawai.txtEmpName.columnName")); // NOI18N
        txtEmpName.setDataSet(emp.getDataSet());
        txtEmpName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmpNameActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Bitstream Vera Sans", 0, 11)); // NOI18N
        jLabel3.setText(org.openide.util.NbBundle.getMessage(FrmPegawai.class, "FrmPegawai.jLabel3.text")); // NOI18N

        TxtPhone.setText(org.openide.util.NbBundle.getMessage(FrmPegawai.class, "FrmPegawai.TxtPhone.text")); // NOI18N
        TxtPhone.setColumnName(org.openide.util.NbBundle.getMessage(FrmPegawai.class, "FrmPegawai.TxtPhone.columnName")); // NOI18N
        TxtPhone.setDataSet(emp.getDataSet());
        TxtPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtPhoneActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Bitstream Vera Sans", 0, 11)); // NOI18N
        jLabel4.setText(org.openide.util.NbBundle.getMessage(FrmPegawai.class, "FrmPegawai.jLabel4.text")); // NOI18N

        txtMobile.setText(org.openide.util.NbBundle.getMessage(FrmPegawai.class, "FrmPegawai.txtMobile.text")); // NOI18N
        txtMobile.setColumnName(org.openide.util.NbBundle.getMessage(FrmPegawai.class, "FrmPegawai.txtMobile.columnName")); // NOI18N
        txtMobile.setDataSet(emp.getDataSet());
        txtMobile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMobileActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Bitstream Vera Sans", 0, 11)); // NOI18N
        jLabel5.setText(org.openide.util.NbBundle.getMessage(FrmPegawai.class, "FrmPegawai.jLabel5.text")); // NOI18N

        txtEmail.setText(org.openide.util.NbBundle.getMessage(FrmPegawai.class, "FrmPegawai.txtEmail.text")); // NOI18N
        txtEmail.setColumnName(org.openide.util.NbBundle.getMessage(FrmPegawai.class, "FrmPegawai.txtEmail.columnName")); // NOI18N
        txtEmail.setDataSet(emp.getDataSet());
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });

        txtAlamat.setFont(new java.awt.Font("Bitstream Vera Sans", 0, 11)); // NOI18N
        txtAlamat.setText(org.openide.util.NbBundle.getMessage(FrmPegawai.class, "FrmPegawai.txtAlamat.text")); // NOI18N

        jdbTextArea1.setColumns(20);
        jdbTextArea1.setRows(5);
        jdbTextArea1.setColumnName(org.openide.util.NbBundle.getMessage(FrmPegawai.class, "FrmPegawai.jdbTextArea1.columnName")); // NOI18N
        jdbTextArea1.setDataSet(emp.getDataSet());
        jScrollPane1.setViewportView(jdbTextArea1);

        txtCity.setFont(new java.awt.Font("Bitstream Vera Sans", 0, 11)); // NOI18N
        txtCity.setText(org.openide.util.NbBundle.getMessage(FrmPegawai.class, "FrmPegawai.txtCity.text")); // NOI18N

        jCboCity1.setColumnName(org.openide.util.NbBundle.getMessage(FrmPegawai.class, "FrmPegawai.jCboCity1.columnName")); // NOI18N
        jCboCity1.setDataSet(emp.getDataSet());

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtAlamat, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtCity, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE))
                            .addComponent(jCboCity1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtEmpName, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                            .addComponent(bTextIDField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMobile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TxtPhone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(105, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(bTextIDField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmpName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMobile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(txtAlamat))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCboCity1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCity))))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jBToolbar3, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 26, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jFormLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(33, 33, 33))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jBToolbar3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jFormLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bTextIDField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTextIDField3ActionPerformed
        
    }//GEN-LAST:event_bTextIDField3ActionPerformed

    private void txtEmpNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmpNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmpNameActionPerformed

    private void TxtPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtPhoneActionPerformed

    private void txtMobileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMobileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMobileActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void jBToolbar3ToolbarNewPerformed(com.bits.lib.dbswing.JBToolbarEvent evt) {//GEN-FIRST:event_jBToolbar3ToolbarNewPerformed
        doNew();
    }//GEN-LAST:event_jBToolbar3ToolbarNewPerformed

    private void jBToolbar3ToolbarCancelPerformed(com.bits.lib.dbswing.JBToolbarEvent evt) {//GEN-FIRST:event_jBToolbar3ToolbarCancelPerformed
        doCancel();
    }//GEN-LAST:event_jBToolbar3ToolbarCancelPerformed

    private void jBToolbar3ToolbarDeletePerformed(com.bits.lib.dbswing.JBToolbarEvent evt) {//GEN-FIRST:event_jBToolbar3ToolbarDeletePerformed
        doDelete();
    }//GEN-LAST:event_jBToolbar3ToolbarDeletePerformed

    private void jBToolbar3ToolbarEditPerformed(com.bits.lib.dbswing.JBToolbarEvent evt) {//GEN-FIRST:event_jBToolbar3ToolbarEditPerformed
        doEdit(bTextIDField3.getText());
    }//GEN-LAST:event_jBToolbar3ToolbarEditPerformed

    private void jBToolbar3ToolbarOpenPerformed(com.bits.lib.dbswing.JBToolbarEvent evt) {//GEN-FIRST:event_jBToolbar3ToolbarOpenPerformed
        doOpen();
    }//GEN-LAST:event_jBToolbar3ToolbarOpenPerformed

    private void jBToolbar3ToolbarSavePerformed(com.bits.lib.dbswing.JBToolbarEvent evt) {//GEN-FIRST:event_jBToolbar3ToolbarSavePerformed
        doSave();
    }//GEN-LAST:event_jBToolbar3ToolbarSavePerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.bits.lib.dbswing.JBdbTextField TxtPhone;
    private com.bits.bee.ui.myswing.BTextIDField bTextIDField3;
    private com.bits.lib.dbswing.JBToolbar jBToolbar3;
    private com.bits.bee.ui.myswing.JCboCity jCboCity1;
    private com.bits.bee.ui.myswing.JFormLabel jFormLabel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private com.borland.dbswing.JdbTextArea jdbTextArea1;
    private javax.swing.JLabel txtAlamat;
    private javax.swing.JLabel txtCity;
    private com.bits.lib.dbswing.JBdbTextField txtEmail;
    private com.bits.lib.dbswing.JBdbTextField txtEmpName;
    private com.bits.lib.dbswing.JBdbTextField txtMobile;
    // End of variables declaration//GEN-END:variables

    @Override
    public void doNew() {
        emp.getDataSet().emptyAllRows();
        emp.New();
        emp.setString("empid", "AUTO");
        emp.setTransCode("PGW");
        state.setState(BdbState.stNEW);
    }

    @Override
    public void doOpen() {
        DlgPegawai dlg = DlgPegawai.getInstance();
        dlg.setVisible(true);
        if (dlg.getSelectedID() != null) {
            try {
                emp.LoadID(dlg.getSelectedID());
                state.setState(BdbState.stEDIT);
            } catch (Exception ex) {
                Exceptions.printStackTrace(ex);
            }
        }
    }

    @Override
    public void doEdit() {
        state.setState(BdbState.stEDIT);
    }

    @Override
    public void doEdit(String id) {
        if(id != null){
            try {
                emp.LoadID(id);
                state.setState(BdbState.stEDIT);
            } catch (Exception ex) {
                Exceptions.printStackTrace(ex);
            }            
        }
    }

    @Override
    public void doSave() {
        try {
            emp.saveChanges();
            UIMgr.showMessageDialog("Data berhasil Disimpan");
            state.setState(BdbState.stNONE);
        } catch (Exception ex) {
            UIMgr.showErrorDialog("Error", ex);
        }

    }

    @Override
    public void doCancel() {
        state.setState(BdbState.stNONE);
    }

    @Override
    public void doDelete() {
        try {
            emp.getDataSet().deleteRow();
            emp.saveChanges();
            UIMgr.showMessageDialog("Data Berhasil dihapus");
            state.setState(BdbState.stNONE);
        } catch (Exception ex) {
            Exceptions.printStackTrace(ex);
        }

    }

    @Override
    public void doVoid() {
    }

    @Override
    public void doPrint() {
    }

    @Override
    public void doRefresh() {
    }

    @Override
    public void setTransState(int state) {
        this.state.setState(state);
    }

    @Override
    public void propertyChange(PropertyChangeEvent evt) {
        if (evt.getPropertyName().equalsIgnoreCase("state")) {
            if (state.getState() == BdbState.stNEW || state.getState() == BdbState.stEDIT) {
                initPanel(true);
                jBToolbar3.setEnableEdit(false);
            } else {
                jBToolbar3.setEnableEdit(true);
                initPanel(false);
            }
        }
    }
}
